runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "lightscreenbucket"

handlers:
- url: /
  secure: always
  static_files: dist/svg-design-demo/index.html
  upload: dist/svg-design-demo/.*
- url: /assets
  static_dir: dist/svg-design-demo/assets
- url: /(.*\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/svg-design-demo/\1
  upload: dist/svg-design-demo/.*\.js
- url: /(.*\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/svg-design-demo/\1
  mime_type: text/css
  upload: dist/svg-design-demo/.*\.css
- url: /.*
  secure: always
  static_files: dist/svg-design-demo/index.html
  upload: dist/svg-design-demo/.*